apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-pro-kube-prometheus-sta-general.rules
  namespace: default
  labels:
    app: kube-prometheus-stack
    release: my-pro
spec:
  groups:
    - name: example
      rules:
        - alert: TestMessage
          expr: vector(1)
          for: 10s
          labels:
            severity: none
          annotations:
            summary: "This is a test message"
            description: "This alert is triggered every 10 seconds."
        - alert: PodCrashLooping
          annotations:
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping.
            summary: Pod is crash looping
          expr: kube_pod_container_status_restarts_total{job="kube-state-metrics"} > 1
          for: 1m
          labels:
            severity: critical
        - alert: PodDeleted
          expr: (sum(kube_pod_status_phase{phase="Running"}) - sum(kube_pod_status_phase{phase="Running"} offset 5m)) < -1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "A pod has been deleted"
            description: "The number of running pods has decreased by at least 1 within the last 5 minutes."
    - name: general.rules
      rules:
        - alert: TargetDown
          annotations:
            description: '{{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are down.'
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/targetdown
            summary: One or more targets are unreachable.
          expr: 100 * (count(up == 0) BY (cluster, job, namespace, service) / count(up) BY (cluster, job, namespace, service)) > 10
          for: 10m
          labels:
            severity: warning
        - alert: Watchdog
          annotations:
            description: This alert ensures the alerting pipeline is functional. It should always be firing.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/watchdog
            summary: Alertmanager functionality verification.
          expr: vector(1)
          labels:
            severity: none
        - alert: InfoInhibitor
          annotations:
            description: Used to inhibit info alerts. Fires when there's a severity="info" alert and stops when a 'warning' or 'critical' alert starts in the same namespace.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/infoinhibitor
            summary: Info-level alert inhibition.
          expr: ALERTS{severity = "info"} == 1 unless on(namespace) ALERTS{alertname != "InfoInhibitor", severity =~ "warning|critical", alertstate="firing"} == 1
          labels:
            severity: none
        - alert: KubePodCrashLooping
          annotations:
            description: KubePodCrashLooping
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepodcrashlooping
            summary: KubePodCrashLooping
          expr: |
            sum by(namespace, pod) (kube_pod_container_status_restarts_total) > 5
          for: 5m
          labels:
            severity: critical
          